# Generated by Django 5.0.1 on 2024-01-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
    ]
